site_name: ShapleyX Documentation
site_url: https://frederickbennett.github.io/shapleyx/
repo_url: https://github.com/frederickbennett/shapleyx

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: true
            heading_level: 3

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Tutorials:
    - Basic Usage: tutorials/basic-usage.md
  - How-to Guides:
    - Common Tasks: how-to-guides/common-tasks.md
  - Reference:
    - API: reference/api.md
  - Explanation:
    - Theory: explanation/theory.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.snippets
  - attr_list